### ISSUE TITLE
Если "Bad request" то нужно выставлять статус 400

### ISSUE THREAD

**Issue by coursar** [lowerKamaCase/09-backend#1]
https://github.com/lowerKamaCase/09-backend/blob/b9041b9e4263d4f88cf5fb20fa655ec2d243b176/app.js#L118

**Comment by lowerKamaCase** [comment]
Коммент убран.
На фронтэнде в setinterval'е есть проверка на длину массива, поэтому в данном месте отправляю пустой массив.

**Comment by coursar** [comment]
Это логически не совсем правильно - обычно, если ошибка, то отправляют текст ошибки, а не данные.

**Comment by lowerKamaCase** [comment]
Bad request added :)
